Add support Android 11
JesusFreke/smali pull request #799
Opened 2020-12-30 20:48 UTC by MrIkso

Fix #798

2020-12-30 21:45 UTC, strazzere commented on dexlib2/src/main/java/org/jf/dexlib2/HiddenApiRestriction.java
> +        if (domainSpecificPart == 0 | domainSpecificPart != value) {
Should this not be a logical or (`||`) instead of a bitwise or (`|`)?

2020-12-30 21:57 UTC, JesusFreke requested changes

2020-12-30 21:57 UTC, JesusFreke commented on dexlib2/src/main/java/org/jf/dexlib2/writer/DexWriter.java
> -        return hasHiddenApiRestrictions && opcodes.api >= 29;
I'm pretty sure  this should stay as 29? Otherwise this will change the behavior for api 29.

2020-12-30 21:57 UTC, JesusFreke commented on smali/src/main/jflex/smaliLexer.jflex
> -        if (apiLevel < 30) {
Ditto above comment

2020-12-30 21:57 UTC, JesusFreke commented on dexlib2/src/main/java/org/jf/dexlib2/HiddenApiRestriction.java
> +    CORE_PLATFORM_API(9, "core-platform-api", true);
Why are you changing the value of core-platform-api? The first 3 bits are for the api white/black/greylist values, and then the 4th bit (mask value 8) is for the core-platform-api flag. And it looks like there's a new flag value for android 11, for "test-api".

See, e.g. https://android.googlesource.com/platform/art/+/267366ca19e7b71a63d3c4a02976cc56a6e58adc/libartbase/base/hiddenapi_flags.h#110

2020-12-30 21:57 UTC, JesusFreke commented on dexlib2/src/main/java/org/jf/dexlib2/HiddenApiRestriction.java
> +        return ImmutableSet.of(normalRestriction, domainSpecificApiFlags[(domainSpecificPart >> 4) - 1]);
The normal api flags still use the first 3 bits, with the domain specific flags starting on the 4th bit. Shifting by 4 will shift off the first bit of the domain specific part.

2020-12-30 21:57 UTC, JesusFreke commented on dexlib2/src/main/java/org/jf/dexlib2/HiddenApiRestriction.java
> +        if (domainSpecificPart == 0 | domainSpecificPart != value) {
???

2020-12-30 21:57 UTC, JesusFreke commented on smali/src/main/antlr/smaliTreeWalker.g
> -          if (opcodes.api < 29) {
ditto above comment.

2020-12-30 21:57 UTC, JesusFreke commented on smali/src/main/jflex/smaliLexer.jflex
> +    "whitelist" | "greylist" | "blacklist" | "greylist-max-o" | "greylist-max-p" | "greylist-max-q" | "greylist-max-r" |
The new value needs to be added to smali as well.

2020-12-31 10:10 UTC, MrIkso commented
Yes, maybe changes incorrect, but it works on dex from android 11. I think  about close this pull, so that @JesusFreke create normal and correct fix.

2020-12-31 15:13 UTC, pashamcr commented
@JesusFreke, happy New Year!
I will assume the presence of dex40
https://source.android.com/devices/tech/dalvik/dex-format#simplename
_VersionMap.java_

2021-01-01 12:11 UTC, MrIkso commented
My changes not correct.

2021-01-01 12:11 UTC, closed without merging

2021-02-18 00:20 UTC, JesusFreke commented
Support for the new test-api hidden api restriction was added in 812bf35149975b15186506f28feecf35dc23128c